# Site settings
title: 5thingsAngular
description: > # this means to ignore newlines until "baseurl:"
  Get weekly updates on 5 things Angular
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://5thingsAngular.github.io" # the base hostname & protocol for your site
twitter_username: 5thingsAngular
github_username:  5thingsAngular

# Build settings
markdown: kramdown
